package com.seifmortada.applications.quran.presentation.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_primary = Color(0xFF3F6900)
val md_theme_onPrimary = Color(0xFFFFFFFF)
val md_theme_primaryContainer = Color(0xFF6FAE19)
val md_theme_onPrimaryContainer = Color(0xFF071200)
val md_theme_secondary = Color(0xFF4B662A)
val md_theme_onSecondary = Color(0xFFFFFFFF)
val md_theme_secondaryContainer = Color(0xFFD0F2A5)
val md_theme_onSecondaryContainer = Color(0xFF385217)
val md_theme_tertiary = Color(0xFF006C50)
val md_theme_onTertiary = Color(0xFFFFFFFF)
val md_theme_tertiaryContainer = Color(0xFF24B087)
val md_theme_onTertiaryContainer = Color(0xFF00110A)
val md_theme_error = Color(0xFFBA1A1A)
val md_theme_onError = Color(0xFFFFFFFF)
val md_theme_background = Color(0xFFF7FBEA)
val md_theme_onBackground = Color(0xFF191D13)
val md_theme_surface = Color(0xFFF7FBEA)
val md_theme_onSurface = Color(0xFF191D13)
val md_theme_surfaceVariant = Color(0xFFDEE6CD)
val md_theme_onSurfaceVariant = Color(0xFF424937)
val md_theme_outline = Color(0xFF727A66)
val md_theme_inverseSurface = Color(0xFF2E3227)
val md_theme_inverseOnSurface = Color(0xFFEFF3E2)
val md_theme_inversePrimary = Color(0xFF97D945)